#!/bin/bash -e

OPS_MGR_HOST=
OPS_MGR_USR=
OPS_MGR_PWD=

PRODUCTS_DEPLOYED=$(om -k -t $OPS_MGR_HOST -u $OPS_MGR_USR -p $OPS_MGR_PWD curl -path /api/v0/deployed/products -s)

INSTALLATION_NAMES=$(echo "$PRODUCTS_DEPLOYED" | jq -r '.[].installation_name')

echo "$INSTALLATION_NAMES" | while read INSTALLATION_NAME
do
  if [[ "$INSTALLATION_NAME" != "p-bosh" ]]; then
    PRODUCT_RESOURCES=$(om -k -t $OPS_MGR_HOST -u $OPS_MGR_USR -p $OPS_MGR_PWD curl -path /api/v0/staged/products/$INSTALLATION_NAME/resources -s)
    PRODUCT_TYPE=$(echo "$PRODUCTS_DEPLOYED" | jq -r --arg installation_name "$INSTALLATION_NAME" '.[] | select(.installation_name | contains($installation_name)) | .type')

    echo "$PRODUCT_RESOURCES" > $PRODUCT_TYPE-resources.json
  fi
done

echo "Successfully took dump of the resource settings"
