#!/bin/bash

FILE=$1
PRODUCT_NAME=$2

if [[ -z "$FILE" ]]; then
  echo "Provided file $FILE does not exist."
  exit 1
fi

UPDATED_JSON=$(cat $FILE | jq -L $PWD 'import "library" as lib;
   lib::walk(if type == "object" then del(.type) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
   lib::walk(if type == "object" then del(.optional) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.credential) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.guid) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.options) else . end)')

KEYS=$(echo "$UPDATED_JSON" | jq -r '.[] | keys[]')

for i in $(echo $KEYS | sed "s/,/ /g")
do
    KEY=$(echo $i)
    IS_NON_CONFIGURABLE=$(echo "$UPDATED_JSON" | jq --arg "key" "$KEY" '.properties[$key] | select(.configurable==false)')
    if [[ ! -z "$IS_NON_CONFIGURABLE" ]]; then
      UPDATED_JSON=$(echo "$UPDATED_JSON" | jq --arg "key" "$KEY" 'del(.properties[$key])')
    fi
done

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.configurable) else . end)')

echo "$UPDATED_JSON" | jq '.[]' > $PRODUCT_NAME-modified.json
