#!/bin/bash

PROPERTIES_FILE=$1
RESOURCES_FILE=$2
PRODUCT_NAME=$3
OUTPUT_DIR=$4

if [ ! -d "$OUTPUT_DIR/modified" ]; then
    mkdir -p $OUTPUT_DIR/modified
fi

if [[ -z "$PROPERTIES_FILE" ]]; then
  echo "Provided file $PROPERTIES_FILE does not exist."
  exit 1
fi

UPDATED_JSON=$(cat $PROPERTIES_FILE | jq -L $PWD 'import "library" as lib;
   lib::walk(if type == "object" then del(.type) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
   lib::walk(if type == "object" then del(.optional) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.credential) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.guid) else . end)')

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.options) else . end)')

KEYS=$(echo "$UPDATED_JSON" | jq -r '.[] | keys[]')

for i in $(echo $KEYS | sed "s/,/ /g")
do
    KEY=$(echo $i)
    IS_NON_CONFIGURABLE=$(echo "$UPDATED_JSON" | jq --arg "key" "$KEY" '.properties[$key] | select(.configurable==false)')
    if [[ ! -z "$IS_NON_CONFIGURABLE" ]]; then
      UPDATED_JSON=$(echo "$UPDATED_JSON" | jq --arg "key" "$KEY" 'del(.properties[$key])')
    fi
done

UPDATED_JSON=$(echo "$UPDATED_JSON" | jq -L $PWD 'import "library" as lib;
  lib::walk(if type == "object" then del(.configurable) else . end)')

echo "$UPDATED_JSON" | jq '.[]' > $OUTPUT_DIR/modified/$PRODUCT_NAME.json

./convert-json $OUTPUT_DIR/modified/$PRODUCT_NAME.json $RESOURCES_FILE $PRODUCT_NAME $OUTPUT_DIR
