#!/bin/bash -ex

source ../env

if [ ! -d "$OUTPUT_DIR/original" ]; then
    mkdir -p "$OUTPUT_DIR/original"
fi

PRODUCTS=$(om -t $OPS_MGR_HOST -u $OPS_MGR_USERNAME -p $OPS_MGR_PASSWORD -k curl -p /api/v0/staged/products)

PRODUCT_GUIDS=$(echo $PRODUCTS | jq -r '.[] | .guid')

for i in $(echo $PRODUCT_GUIDS)
do
    PRODUCT_GUID=$(echo $i)
    PRODUCT_NAME=$(echo $PRODUCTS | jq -r --arg product_guid $i '.[] | select(.guid==$product_guid) | .type')
    if [[ "$PRODUCT_NAME" != "p-bosh" ]]; then
      PRODUCT_PROPERTIES=$(om -t $OPS_MGR_HOST -u $OPS_MGR_USERNAME -p $OPS_MGR_PASSWORD -k curl -p /api/v0/staged/products/$PRODUCT_GUID/properties)
      echo "$PRODUCT_PROPERTIES" > $OUTPUT_DIR/original/$PRODUCT_NAME.json

      PRODUCT_RESOURCES=$(om -t $OPS_MGR_HOST -u $OPS_MGR_USERNAME -p $OPS_MGR_PASSWORD -k curl -p /api/v0/staged/products/$PRODUCT_GUID/resources)
      echo "$PRODUCT_RESOURCES" > $OUTPUT_DIR/original/$PRODUCT_NAME-resources.json

      cd ../clean-up-pipelines-json/
      ./cleanup-json $OUTPUT_DIR/original/$PRODUCT_NAME.json $OUTPUT_DIR/original/$PRODUCT_NAME-resources.json $PRODUCT_NAME $OUTPUT_DIR
    fi
done
