#!/bin/bash

PROPERTIES_FILE=$1
RESOURCES_FILE=$2
PRODUCT_NAME=$3
OUTPUT_DIR=$4

COMMON_VARIABLES=("OPS_MGR_HOST" "OPS_MGR_USR" "OPS_MGR_PWD" "NETWORK_NAME" "OTHER_AZS" "SINGLETON_JOBS_AZ" "PRODUCT_NAME")

if [ ! -d "$OUTPUT_DIR/tasks/config-$PRODUCT_NAME" ]; then
    mkdir -p "$OUTPUT_DIR/tasks/config-$PRODUCT_NAME"
fi

OUTFILE="$OUTPUT_DIR/tasks/config-$PRODUCT_NAME/task.sh"
OUTFILE_YML="$OUTPUT_DIR/tasks/config-$PRODUCT_NAME/task.yml"

touch "$OUTFILE"
touch "$OUTFILE_YML"

echo "---" >> "$OUTFILE_YML"
echo -e '\n' >> "$OUTFILE_YML"
echo "platform: linux" >> "$OUTFILE_YML"
echo -e '\n' >> "$OUTFILE_YML"
echo "image_resource:" >> "$OUTFILE_YML"
echo "  type: docker-image" >> "$OUTFILE_YML"
echo "  source: {repository: rjain/buildbox}" >> "$OUTFILE_YML"
echo -e '\n' >> "$OUTFILE_YML"
echo "params:" >> "$OUTFILE_YML"

for variable in ${COMMON_VARIABLES[@]}; do
  echo "  $variable:" >> "$OUTFILE_YML"
done

echo -e "#!/bin/bash\n\n" >> "$OUTFILE"

## Properties

echo 'properties_config=$(jq -n \' >> "$OUTFILE"

val='{"value": "$\(.key | split(".") | .[-1])"}'
IFS='' read -r -d '' CONVERT_SCRIPT << EOF
to_entries |
map(
    if (.value.value | type) == "object"
    then . + {"value": {"secret": $val}}
    else . + {"value": $val} end
) |
from_entries
EOF

ARGS=
KEYS=$(cat "$PROPERTIES_FILE" | $JQ_CMD -r 'keys[] | split(".") | .[-1]')
JSON=$(cat "$PROPERTIES_FILE" | $JQ_CMD "$CONVERT_SCRIPT" | sed 's/\"\(\$.*\)\"/\1/g')

for key in $KEYS; do
  echo "  --arg $key \$$(echo $key | awk '{print toupper($0)}') \\" >> "$OUTFILE"
  echo "  $(echo $key | awk '{print toupper($0)}'):" >> "$OUTFILE_YML"
done

echo "'$JSON'" >> "$OUTFILE"

echo -e ')\n\n' >> "$OUTFILE"

echo -e '\n' >> "$OUTFILE_YML"
echo "inputs:" >> "$OUTFILE_YML"
echo "  - name: pipelines-repo" >> "$OUTFILE_YML"
echo "  - name: om-cli" >> "$OUTFILE_YML"
echo "  - name: $JQ_CMD" >> "$OUTFILE_YML"
echo -e '\n' >> "$OUTFILE_YML"
echo "run:" >> "$OUTFILE_YML"
echo "  path: pipelines-repo/tasks/config-$PRODUCT_NAME/task.sh" >> "$OUTFILE_YML"

## Resources

echo 'resources_config="{' >> "$OUTFILE"

KEYS=$(cat "$RESOURCES_FILE" | $JQ_CMD -r '.resources | .[] | .identifier' )
j=$(cat $RESOURCES_FILE | $JQ_CMD '.resources | length')

i=1
for key in $KEYS; do
  echo -n "  \\\"$key\\\": {\\\"instances\\\": \$$(echo $key | sed 's/-/_/g' | awk '{print toupper($0)}')_INSTANCES}" >> "$OUTFILE"

  if [ $((i)) -ne $((j)) ]; then
      echo -n "," >> "$OUTFILE"
  fi

  i=$((i+1))

  echo >> "$OUTFILE"
done
unset i j

echo -e '}"\n\n' >> "$OUTFILE"

## Network

echo 'network_config=$(jq -n \' >> "$OUTFILE"
echo '  --arg network_name "$NETWORK_NAME" \ ' >> "$OUTFILE"
echo '  --arg other_azs "$OTHER_AZS" \ ' >> "$OUTFILE"
echo '  --arg singleton_az "$SINGLETON_JOBS_AZ" \ ' >> "$OUTFILE"
echo "'" >> "$OUTFILE"
echo '  {' >> "$OUTFILE"
echo '    "network": {' >> "$OUTFILE"
echo '      "name": $network_name' >> "$OUTFILE"
echo '    },' >> "$OUTFILE"
echo '    "other_availability_zones": ($other_azs | split(",") | map({name: .})),' >> "$OUTFILE"
echo '    "singleton_availability_zone": {' >> "$OUTFILE"
echo '      "name": $singleton_az' >> "$OUTFILE"
echo '    }' >> "$OUTFILE"
echo '  }' >> "$OUTFILE"
echo "'" >> "$OUTFILE"
echo -e ')\n\n' >> "$OUTFILE"

## Run

echo 'om-linux \' >> "$OUTFILE"
echo '  --target https://$OPSMAN_DOMAIN_OR_IP_ADDRESS \' >> "$OUTFILE"
echo '  --username "$OPS_MGR_USR" \' >> "$OUTFILE"
echo '  --password "$OPS_MGR_PWD" \' >> "$OUTFILE"
echo '  --skip-ssl-validation \' >> "$OUTFILE"
echo '  configure-product \' >> "$OUTFILE"
echo "  --product-name $PRODUCT_NAME \\" >> "$OUTFILE"
echo '  --product-properties "$properties_config" \' >> "$OUTFILE"
echo '  --product-network "$network_config" \' >> "$OUTFILE"
echo '  --product-resources "$resources_config"' >> "$OUTFILE"
