#!/bin/bash -e

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/.init.sh

if [ -d "$OUTPUT_DIR" ]; then
  log "Purging exsting OUTPUT_DIR: $OUTPUT_DIR"
  rm -rf "$OUTPUT_DIR"
fi

if [ ! -d "$OUTPUT_DIR/original" ]; then
  log "Creating directory $OUTPUT_DIR/original"
  mkdir -p "$OUTPUT_DIR/original"
fi

PRODUCTS=$($CURL_CMD -path /api/v0/staged/products)
PRODUCT_GUIDS=$(echo $PRODUCTS | $JQ_CMD -r '.[] | .guid')

for i in $(echo $PRODUCT_GUIDS)
do
  PRODUCT_GUID=$(echo $i)
  PRODUCT_NAME=$(echo $PRODUCTS | $JQ_CMD -r --arg product_guid $i '.[] | select(.guid==$product_guid) |.type')
  if [[ "$PRODUCT_NAME" != "p-bosh" ]]; then
    echo "--------------------------------------------------------------------------------------------"
    echo "Working on $PRODUCT_NAME"

    PRODUCT_PROPERTIES=$($CURL_CMD -path /api/v0/staged/products/$PRODUCT_GUID/properties)
    echo "$PRODUCT_PROPERTIES" > "$OUTPUT_DIR/original/$PRODUCT_NAME.json"

    PRODUCT_RESOURCES=$($CURL_CMD -path /api/v0/staged/products/$PRODUCT_GUID/resources)
    echo "$PRODUCT_RESOURCES" > "$OUTPUT_DIR/original/$PRODUCT_NAME-resources.json"

    "$(dirname "$0")"/cleanup-json "$OUTPUT_DIR/original/$PRODUCT_NAME.json" "$PRODUCT_NAME"
    "$(dirname "$0")"/generate-tasks "$OUTPUT_DIR/modified/$PRODUCT_NAME.json" "$OUTPUT_DIR/original/$PRODUCT_NAME-resources.json" "$PRODUCT_NAME"

    echo "Tasks for the $PRODUCT_NAME are located in $OUTPUT_DIR/tasks/config-$PRODUCT_NAME"
    echo "--------------------------------------------------------------------------------------------"
  fi
done
