#!/bin/bash -e

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/.init.sh

dependency $OM_CMD $JQ_CMD curl

PRODUCTS_DEPLOYED=$($CURL_CMD -path /api/v0/deployed/products)
INSTALLATION_NAMES=$(echo "$PRODUCTS_DEPLOYED" | $JQ_CMD -r '.[].installation_name')

echo "$INSTALLATION_NAMES" | while read INSTALLATION_NAME; do
  if [ "$INSTALLATION_NAME" != "p-bosh" ]; then
    PRODUCT_RESOURCES=$($CURL_CMD -path /api/v0/staged/products/"$INSTALLATION_NAME"/resources -s)
    PRODUCT_TYPE=$(echo "$PRODUCTS_DEPLOYED" | $JQ_CMD -r --arg installation_name "$INSTALLATION_NAME" '.[] | select(.installation_name | contains($installation_name)) | .type')

    echo "$PRODUCT_RESOURCES" > "$OUTPUT_DIR/$PRODUCT_TYPE-resources.json"
  fi
done

echo "Successfully took dump of the resource settings"
